### PR TITLE
Add Social Worker Services

### LINKED ISSUE #37: Add Emergency Service for Social Workers
Sometimes folks are experiencing a mental health crisis or another incident of which only requires someone with counseling experience to assist. Depending on the municipality, Social Workers may work within a Police Department, Homelessness Services or a separate department or unit specific to Social Work.

### PR DESCRIPTION
**Pull request by csharpie**
Added Social Worker Services as an option to select. Updated the Response Dispatch Flow to have this option as a path within the Response Task Generation's Flow Action. Added a new Decision Table condition in the Department Selection table. Added a Choice list option for the Response dispatched field on x_snc_911_operat_0_emergency.

I also swapped in the data pill for the Emergency Task's Response dispatched field onto the Response Task Generation's Flow Action as the value for the Decision table input.

After running a test for Social Worker Services from the Response Dispatch Flow, the flow correctly created a Service Task.

Resolves #37

### CODE REVIEW

**Comment by csharpie** [comment]
I want to associate this with #37

**Review by SapphicFire — APPROVED** [review]
Thank you for the contribution, nice work :)

**Comment by SapphicFire** [comment]
For future reference, there are a few keywords you can use in your PR such as 'resolves' and 'fixes' to link to the issue and auto-close it :)

**Comment by csharpie** [comment]
Thanks @SapphicFire. I will definitely use those keywords on subsequent PRs.

**Pull request merged**
